openapi: "3.0.0"
info:
  version: 2.0.0
  title: Order API
paths:
  /order:
    post:
      summary: Api rest that allows us to order the "pilotes" of the great Miquel Montoro
      operationId: orderPilotes
      requestBody:
        description: A valid client, product, only "Pilotes" in stock for now, and a quantity bigger than one
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequest"
            example:
              clientId: 1
              productId: 1
              quantity: 2
      responses:
        "200":
          description: Pilotes were successfully ordered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
                example:
                  orderNumer: 123456
                  clientId: 1
                  productId: 1
                  quantity: 2
                  orderTotal: 22.50
        "400":
          description: 400 error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: 1
                message: Bad request
        "404":
          description: 404 error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: 2
                message: Not Found
        "500":
          description: 500 error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: 3
                message: Some internal error
components:
  schemas:
    OrderRequest:
      type: object
      required:
        - clientId
        - productId
        - quantity
      properties:
        clientId:
          type: integer
          format: int64
          description: A valid Client code
        productId:
          type: integer
          format: int64
          description: A valid Product code
        quantity:
          type: integer
          format: int64
          minimum: 1
          description: A bigger than one quantity
    OrderResponse:
      type: object
      required:
        - orderNumber
        - clientId
        - productId
        - quantity
        - orderTotal
      properties:
        orderNumber:
          type: string
          description:
        clientId:
          type: integer
          format: int64
          description: The client for whom the product was order
        productId:
          type: integer
          format: int64
          description: The rated product code
        quantity:
          type: integer
          format: int64
          description: The quantity of the product
        orderTotal:
          type: number
          format: float
          description: The monetary amount according to the price and quantity
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: The error code
        message:
          type: string
          description: A detail of what happened